#[derive(Debug, Clone)]
pub enum SchedMsg {
    Close,
    Submit,
    SetEnabled(bool),
    SetRuleEnabled(u16, bool),
    ToggleRuleOptions(u16),
    AddRule,
    RemoveRule(u16),
    DragStart(u16),
    DragOver(u16),
    DragEnd,
    EditNode(u16, Vec<u16>),
    EditAdd(u16, Vec<u16>),
    NameInput(u16, String),
    SetInput(u16, String),
    AddBlock(u16, Vec<u16>, u8),
    AddGroup(u16, Vec<u16>, bool),
    RemoveNode(u16, Vec<u16>),
    ToggleVal(u16, Vec<u16>, String),
    TimePart(u16, Vec<u16>, u8, String),
    TextBlock(u16, Vec<u16>, String),
    BlockChoice(u16, Vec<u16>, String),
    Comparison(u16, Vec<u16>, String),
    SetGroupOperator(u16, Vec<u16>, bool),
    SetNegated(u16, Vec<u16>, bool),
    ResetCondition(u16),
    Mode(u16, String),
}
